### ISSUE TITLE
mic + camera streaming

### ISSUE THREAD

**Issue by eadmaster** [priyankark/PhonePiAndroidApp#1]
There 2 sensors can be useful  for many uses...

**Comment by priyankark** [comment]
Thanks a lot for this suggestion! This is something I have my mind on too.
I am planning on starting work on a new version of Phone Pi with better UI and more features. I will incorporate this in that. If you have some suggestions on what protocol to use, do let me know. Best wishes.

**Comment by priyankark** [comment]
Although it's a bit late, a different version of the app now supports Camera and Audio streaming along with other sensors available. (https://play.google.com/store/apps/details?id=com.sensorsensei)
